// Generated types for users
/**
 * @typedef {Object} ComplexType
 * @property {string} id
 * @property {string} name
 * @property {number} age
 * @property {boolean} is_verified
 * @property {string[]} tags [optional]
 * @property {Duration} created_at
 */
class ComplexType {
  constructor(data) {
    this.tags = data.tags;
    this.created_at = data.created_at;
    this.id = data.id;
    this.name = data.name;
    this.age = data.age;
    this.is_verified = data.is_verified;
  }
}

/**
 * @typedef {Object} UserProfile
 * @property {User} user
 */
class UserProfile {
  constructor(data) {
    this.user = data.user;
  }
}

/**
 * @typedef {Object} Address
 * @property {string} street
 * @property {string} city
 * @property {string} country
 */
class Address {
  constructor(data) {
    this.street = data.street;
    this.city = data.city;
    this.country = data.country;
  }
}


// Export all types
export {
    ComplexType,
    UserProfile,
    Address
}




// Types generated by type-utils

